name: 'Run Elasticsearch with Plugins over a proxy'
description: 'Elasticsearch with Plugins downloaded over a proxy'
author: 'JonasGe'

branding:
  icon: 'database'
  color: 'green'

inputs:
  stack-version:
    description: 'The version of Elasticsearch'
    required: true
  plugins:
    description: 'Elasticsearch plugin strings'
    required: false
    default: ''
  http_proxy_host:
    description: 'HTTP proxy host'
    required: false
    default: ''
  https_proxy_host:
    description: 'HTTPS proxy host'
    required: false
    default: ''
  http_proxy_port:
    description: 'HTTP proxy port'
    required: false
    default: ''
  https_proxy_port:
    description: 'HTTPS proxy port'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STACK_VERSION: ${{ inputs.stack-version }}
    PLUGINS: ${{ inputs.plugins }}
    HTTP_PROXY_HOST: ${{ inputs.http_proxy_host }}
    HTTPS_PROXY_HOST: ${{ inputs.https_proxy_host }}
    HTTP_PROXY_PORT: ${{ inputs.http_proxy_port }}
    HTTPS_PROXY_PORT: ${{ inputs.https_proxy_port }}
