name: 'Run Elasticsearch'
description: 'Elasticsearch with Plugin'
author: 'miyataka'

branding:
  icon: 'database'
  color: 'red'

inputs:
  stack-version:
    description: 'The version of Elasticsearch'
    required: true
  plugins:
    description: 'Elasticsearch plugin strings'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STACK_VERSION: ${{ inputs.stack-version }}
    PLUGINS: ${{ inputs.plugins }}
